# these are the letter to phone definitions I'm using to create a 
# phonetic dictionary



kazakh_table = {"б" => "b ",
                "в" => "v ",
                "г" => "g ",
                "д" => "d ",
                "з" => "z ",
                "к" => "k ",
                "л" => "l ",
                "м" => "m ",
                "н" => "n ",
                "п" => "p ",
                "р" => "r ",
                "с" => "s ",
                "т" => "t ",
                "ф" => "f ",
                "х" => "h ",
                "һ" => "h ", 
                "ж" => "zh ",
                "ц" => "ts ",
                "ч" => "ch ",
                "ш" => "sh ",
                "щ" => "sh ",
                "й" => "j ",
                "ғ" => "gh ",
                "қ" => "kh ",
                "ң" => "ng ",
                "а" => "a ", # vowels
                "ә" => "a ",
                "у" => "u ",
                "ү" => "y ",
                "ұ" => "o ",
                "о" => "o ",
                "ө" => "oe ",
                "э" => "e ",
                "е" => "e ",
                "и" => "i ",
                "і" => "ih ",
                "ы" => "ih ",
                "я" => "j a ", # glide + vowels
                "ё" => "j o ",
                "ю" => "j u ",
                "ь" => "",
                "ъ" => ""}
